
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract nft_tokken {

    struct Token {
        string name;//имя
        string faculty;//факультет
        uint age;//возраст
    }

    Token[] tokensArr;//хранение токенов
    mapping (string=>uint) tokensAndPrice; //цены токена по имени(тк оно уникально по условию)

    // создания токена
    function createToken(string name, string faculty, uint age) public checkNameInTokensArr(true, name){
        tokensArr.push(Token(name, faculty, age));
    }

    // выставить токен на продажу
    function tokenToSale(string name, uint value) public checkNameInTokensArr(false, name){
        tokensAndPrice[name] = value;//добавляем цену для токена
    }

    // ДОП ФУНКЦИИ ДЛЯ ПРОВЕРКИ

    // получаем цену токена по имени
    function getTokenSale(string tokenName) public view returns (uint) {
        return tokensAndPrice[tokenName];
    }

    // получаем тнформацию о токене
    function getTokeninfo(uint tokenId) public view returns (string tokenName,string tokenFaculty, uint tokenAge) {
        tvm.accept();
        tokenName = tokensArr[tokenId].name;
        tokenFaculty = tokensArr[tokenId].faculty;
        tokenAge = tokensArr[tokenId].age;
    }

        /// @dev Contract constructor.
    constructor() public {
        // check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }

    // модификатор проверки существования имни в массиве токенов
    modifier checkNameInTokensArr (bool checkName, string name) {
        for (uint i = 0; i < tokensArr.length; i++) {
            if (tokensArr[i].name == name){// если имя совпадает с каким-либо(существует)
                checkName = !checkName;// переменная проверки наоброт
            }
        }
        require(checkName, 101);
        tvm.accept();
        _;
    }
}
