
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract sampletoken {

    struct Token {
        string name;
        uint power;
    }

    Token[] tokensArr;
    mapping (uint=>uint) tokenToOwner;

    function createTokken(string name, uint power) public{
        tvm.accept();
        tokensArr.push(Token(name, power));
        uint lastKeyNum = tokensArr.length - 1;
        tokenToOwner[lastKeyNum] = msg.pubkey();
    }

    function getTokenOwner(uint tokenId) public view returns (uint) {
        return tokenToOwner[tokenId];
    }

    function getTokeninfo(uint tokenId) public view returns (string tokenName, uint tokenPower) {
        tvm.accept();
        tokenName = tokensArr[tokenId].name;
        tokenPower = tokensArr[tokenId].power;
    }

    function changeOwner(uint tokenId, uint pubkeyOfNewOwner) public {
        require(msg.pubkey() == tokenToOwner[tokenId], 101);
        tvm.accept();
        tokenToOwner[tokenId] = pubkeyOfNewOwner;
    }

    function changePower(uint tokenId, uint power) public {
        require(msg.pubkey() == tokenToOwner[tokenId], 101);
        tvm.accept();
        tokensArr[tokenId].power = power;
    }

        /// @dev Contract constructor.
    constructor() public {
        // check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }
}
