
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;


import "baseStation.sol";
// This is class that describes you smart contract.
contract militaryUnit is gameObject{

    int private attackPower;// переменная для хранения атаки
    int private defensePower;// переменная для хранения защиты

    baseStation myBS;// переменная для хранения базы
    
    function checkAlive() public override{
        tvm.accept();
        if(getHealth()<=0){
            myBS.delUnit(gameObject(msg.sender));
            sendTransactioAndDestroyWallet(msg.sender);
        }
    }

    // атака на другой юнит
    function sendAttack(militaryUnit unitToAttack, int value) private view {
        tvm.accept();
        int at = value - getDefenseValue();
        if(at>0){
            unitToAttack.getAttack(at);// атака на юнит
        }
    }

    // получить значение атаки
    function getAttackValue() public view returns (int){
        tvm.accept();
        return attackPower;
    }

    // получить значение защиты
    function getDefenseValue() public view returns(int){
        tvm.accept();
        return defensePower;
    }

    // задать значение атаки
    function setAttackValue(int attack) public{
        tvm.accept();
        attackPower = attack;
    }
    
    // задать значение защиты
    function setDefenseValue(int defense) public{
        tvm.accept();
        defensePower = defense;
    }
    
}
