
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;


import "baseStation.sol";
// This is class that describes you smart contract.
contract militaryUnit is gameObject{

    uint attackPower;
    uint defensePower;

    baseStation myBS;
    

    function sendAttack(militaryUnit unitToAttack, uint value) private view {
        tvm.accept();
        uint at = value - defensePower;
        if(at>0){
            unitToAttack.getAttack(at);
        }
    }

    // получить значение атаки
    function getAttackValue() public view returns (uint){
        tvm.accept();
        return attackPower;
    }

    // получить значение защиты
    function getDefenseValue() public view returns(uint){
        tvm.accept();
        return defensePower;
    }

    // задать значение атаки
    function setAttackValue(uint attack) public{
        tvm.accept();
        attackPower = attack;
    }
    
    // задать значение защиты
    function setDefenseValue(uint defense) public{
        tvm.accept();
        defensePower = defense;
    }

}
